import Header from "./header.jsx"
import Footer from"./footer.jsx"
function App() {
  return (
    <>
      <Header />
      <div className="uppercase mt-3.5 tracking-widest">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam, quibusdam enim! Adipisci magni quam incidunt recusandae explicabo nulla sapiente sint quia est. Rerum reiciendis veniam sit, quo suscipit possimus autem distinctio quae tempora repellat excepturi magnam pariatur hic obcaecati iste laudantium accusantium aperiam doloremque blanditiis. Accusantium sint repudiandae repellendus non, distinctio quo ex repellat rem dicta ea provident, eius veniam porro libero asperiores. Alias neque at, est id architecto fugit ut rerum, ipsum error quo sed nostrum saepe vitae libero maiores modi hic dolores quas molestias soluta nobis qui dolor tempora praesentium. Omnis veritatis sunt, maiores aperiam dolore totam magnam?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam, quibusdam enim! Adipisci magni quam incidunt recusandae explicabo nulla sapiente sint quia est. Rerum reiciendis veniam sit, quo suscipit possimus autem distinctio quae tempora repellat excepturi magnam pariatur hic obcaecati iste laudantium accusantium aperiam doloremque blanditiis. Accusantium sint repudiandae repellendus non, distinctio quo ex repellat rem dicta ea provident, eius veniam porro libero asperiores. Alias neque at, est id architecto fugit ut rerum, ipsum error quo sed nostrum saepe vitae libero maiores modi hic dolores quas molestias soluta nobis qui dolor tempora praesentium. Omnis veritatis sunt, maiores aperiam dolore totam magnam?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam, quibusdam enim! Adipisci magni quam incidunt recusandae explicabo nulla sapiente sint quia est. Rerum reiciendis veniam sit, quo suscipit possimus autem distinctio quae tempora repellat excepturi magnam pariatur hic obcaecati iste laudantium accusantium aperiam doloremque blanditiis. Accusantium sint repudiandae repellendus non, distinctio quo ex repellat rem dicta ea provident, eius veniam porro libero asperiores. Alias neque at, est id architecto fugit ut rerum, ipsum error quo sed nostrum saepe vitae libero maiores modi hic dolores quas molestias soluta nobis qui dolor tempora praesentium. Omnis veritatis sunt, maiores aperiam dolore totam magnam?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam, quibusdam enim! Adipisci magni quam incidunt recusandae explicabo nulla sapiente sint quia est. Rerum reiciendis veniam sit, quo suscipit possimus autem distinctio quae tempora repellat excepturi magnam pariatur hic obcaecati iste laudantium accusantium aperiam doloremque blanditiis. Accusantium sint repudiandae repellendus non, distinctio quo ex repellat rem dicta ea provident, eius veniam porro libero asperiores. Alias neque at, est id architecto fugit ut rerum, ipsum error quo sed nostrum saepe vitae libero maiores modi hic dolores quas molestias soluta nobis qui dolor tempora praesentium. Omnis veritatis sunt, maiores aperiam dolore totam magnam?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam, quibusdam enim! Adipisci magni quam incidunt recusandae explicabo nulla sapiente sint quia est. Rerum reiciendis veniam sit, quo suscipit possimus autem distinctio quae tempora repellat excepturi magnam pariatur hic obcaecati iste laudantium accusantium aperiam doloremque blanditiis. Accusantium sint repudiandae repellendus non, distinctio quo ex repellat rem dicta ea provident, eius veniam porro libero asperiores. Alias neque at, est id architecto fugit ut rerum, ipsum error quo sed nostrum saepe vitae libero maiores modi hic dolores quas molestias soluta nobis qui dolor tempora praesentium. Omnis veritatis sunt, maiores aperiam dolore totam magnam?
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam, quibusdam enim! Adipisci magni quam incidunt recusandae explicabo nulla sapiente sint quia est. Rerum reiciendis veniam sit, quo suscipit possimus autem distinctio quae tempora repellat excepturi magnam pariatur hic obcaecati iste laudantium accusantium aperiam doloremque blanditiis. Accusantium sint repudiandae repellendus non, distinctio quo ex repellat rem dicta ea provident, eius veniam porro libero asperiores. Alias neque at, est id architecto fugit ut rerum, ipsum error quo sed nostrum saepe vitae libero maiores modi hic dolores quas molestias soluta nobis qui dolor tempora praesentium. Omnis veritatis sunt, maiores aperiam dolore totam magnam?
      </div>
      <Footer />
    </>
  )
}

export default App;